language: scala
script:
  - ./bin/runci.sh ci
jdk:
 - oraclejdk8

stages:
  - name: test
  # Disabled till release infrastructure is in place
  #- name: release
  #  if: (branch = master) AND (type = push)

jobs:
  include:
    # default stage is test
    - env: TEST="scalafmt"
      script: ./bin/scalafmt --test
    - env: TEST="sbt test"
      script: sbt test
    - env: TEST="sbt scripted"
      script: sbt scripted
    # release only on merge commits or tags
    #- stage: release
    #  script: if [[ "$(git rev-list --merges HEAD^..HEAD)" || "$TRAVIS_TAG" ]]; then sbt releaseEarly; else echo "skipping release"; fi

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - target/repos
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.ivy2/cache -name "*scalagen*.xml" -type f -delete
  - rm -rf $HOME/.ivy2/local
